id = "RAYTRAC3RSpeciesCompat"
name = "SpeciesCompat"
description = "Lure-based mod that adds compatibility between various modded species and modded patterns."
version = "0.1.0"
homepage = "https://github.com/RAYTRAC3R/SpeciesCompat"
author = "RAYTRAC3R"

icon = "icon.png"
readme = "README.md"
changelog = "CHANGELOG.md" # optional

# both are optional here, pick what you want
[project]
godot = "C:/samidev/SpeciesCompat/project.godot"

[[dependencies]]
thunderstore_version = "NotNet-GDWeave-2.0.12"

# example dependency
[[dependencies]]
id = "Sulayre.Lure"
thunderstore_version = "Sulayre-Lure-3.1.3"